In [43]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [6]:
base_wine = pd.read_csv('winequality-red.csv')
base_wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

DESCRIÇÃO DO DATASET (NENHUM DADO ESPÚRIO)

In [7]:
base_wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [8]:
X_wine_data = base_wine.iloc[:, 0:11].values
X_wine_data

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [9]:
y_wine_data = base_wine.iloc[:, 11].values
y_wine_data

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

Normalização / Padronização dos Dados

In [10]:
from sklearn.preprocessing import StandardScaler
scaler_wine = StandardScaler()
X_wine_data = scaler_wine.fit_transform(X_wine_data)

In [11]:
X_wine_data

array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

Fazendo as divisões das bases (treinamento e teste) 

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_wine_treinamento, X_wine_teste, y_wine_treinamento, y_wine_teste = train_test_split(X_wine_data, y_wine_data ,test_size=0.20,random_state=0)

In [14]:
X_wine_treinamento.shape, X_wine_teste.shape

((1279, 11), (320, 11))

In [15]:
y_wine_treinamento.shape, y_wine_teste.shape

((1279,), (320,))

MODELO NAIVE BAYES

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
naive_wine_data = GaussianNB()
naive_wine_data.fit(X_wine_treinamento, y_wine_treinamento)

GaussianNB()

In [18]:
previsoes_naive_bayes = naive_wine_data.predict(X_wine_teste)
previsoes_naive_bayes

array([5, 5, 7, 5, 7, 5, 5, 6, 5, 5, 5, 5, 6, 4, 6, 7, 7, 6, 6, 5, 6, 5,
       6, 6, 6, 5, 5, 7, 5, 6, 6, 6, 6, 5, 6, 7, 5, 6, 8, 6, 5, 6, 8, 7,
       6, 5, 6, 6, 6, 7, 6, 6, 6, 7, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 7, 6, 6, 5, 4, 5, 5, 5, 8, 5, 5, 5, 7, 6, 5, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 5, 6, 5, 7, 5, 7, 6, 5, 6, 7, 6, 6, 7, 6, 5, 6, 5, 6, 5,
       6, 5, 7, 5, 6, 6, 6, 7, 6, 6, 5, 6, 4, 5, 8, 7, 5, 5, 6, 7, 5, 5,
       6, 6, 7, 5, 7, 4, 7, 6, 6, 5, 6, 6, 5, 6, 7, 7, 6, 6, 6, 6, 5, 5,
       6, 5, 6, 5, 6, 6, 6, 6, 7, 5, 7, 5, 6, 7, 5, 6, 7, 6, 5, 7, 6, 7,
       6, 7, 6, 5, 5, 8, 5, 7, 8, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 7, 6, 5, 6, 7, 4, 7, 5, 5, 6, 6, 6, 5,
       5, 6, 7, 6, 5, 7, 7, 6, 5, 6, 5, 6, 3, 6, 7, 6, 7, 7, 8, 7, 5, 4,
       5, 5, 6, 5, 6, 5, 4, 7, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 8, 5, 6,
       5, 5, 6, 5, 5, 7, 6, 6, 6, 8, 7, 6, 7, 5, 7, 7, 5, 7, 6, 7, 6, 5,
       6, 5, 7, 6, 6, 4, 6, 5, 5, 6, 5, 6, 5, 5, 6,

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
accuracy_score(y_pred=previsoes_naive_bayes, y_true=y_wine_teste)

0.540625

MODELO ARVORE DE DECISÃO

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
tree_wine = DecisionTreeClassifier(criterion='entropy')
tree_wine.fit(X_wine_treinamento, y_wine_treinamento)

DecisionTreeClassifier(criterion='entropy')

In [23]:
previsoes_arvore_unica = tree_wine.predict(X_wine_teste)
previsoes_arvore_unica

array([5, 6, 7, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 4, 5, 7, 7, 6, 5, 5, 7, 6,
       6, 7, 5, 6, 5, 6, 5, 5, 6, 7, 6, 6, 7, 7, 5, 6, 6, 6, 6, 6, 8, 7,
       6, 6, 5, 6, 5, 6, 5, 4, 6, 6, 6, 5, 5, 5, 7, 6, 5, 6, 6, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 4, 5, 6, 5, 5, 5, 5, 7, 6, 5, 6, 5, 6, 6, 7, 5,
       7, 5, 5, 6, 6, 6, 5, 5, 7, 5, 5, 5, 7, 6, 5, 7, 6, 6, 6, 5, 6, 5,
       6, 5, 8, 5, 6, 6, 7, 7, 7, 6, 5, 5, 6, 5, 8, 7, 5, 5, 6, 6, 6, 5,
       6, 6, 6, 5, 6, 5, 7, 5, 6, 5, 5, 5, 5, 6, 8, 6, 5, 5, 6, 5, 5, 6,
       6, 6, 5, 6, 6, 5, 5, 5, 7, 5, 5, 5, 6, 6, 6, 6, 7, 5, 5, 7, 5, 7,
       6, 7, 7, 5, 5, 8, 6, 7, 7, 5, 7, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 8, 5, 6, 5, 6, 6, 5,
       5, 5, 7, 6, 5, 6, 7, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 7, 7, 6, 5, 5,
       4, 5, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 5, 5, 4, 6, 7, 5, 6, 5, 6,
       5, 5, 7, 6, 5, 6, 5, 6, 5, 5, 7, 6, 7, 6, 6, 6, 4, 7, 6, 5, 6, 5,
       5, 6, 7, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6,

In [24]:
accuracy_score(y_pred=previsoes_arvore_unica, y_true=y_wine_teste)

0.603125

MODELO ÁRVORE DE DECISÃO (RANDOM FOREST)

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
random_forest_wine = RandomForestClassifier(n_estimators=300, criterion='entropy', random_state=0)
random_forest_wine.fit(X_wine_treinamento, y_wine_treinamento)

RandomForestClassifier(criterion='entropy', n_estimators=300, random_state=0)

In [28]:
previsoes_random_forest_wine = random_forest_wine.predict(X_wine_teste)
previsoes_random_forest_wine

array([5, 5, 7, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 7, 7, 5, 5, 5, 6, 5,
       6, 6, 5, 5, 5, 7, 5, 6, 6, 6, 6, 5, 7, 7, 5, 6, 6, 6, 5, 6, 6, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 5, 7, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 7, 6, 5, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 5, 8, 5, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 6, 7, 5, 5, 6, 6, 6, 5,
       6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 8, 6, 5, 5, 6, 5, 5, 5,
       6, 6, 5, 5, 6, 6, 6, 6, 7, 5, 5, 5, 6, 6, 6, 6, 6, 6, 5, 7, 5, 6,
       5, 7, 7, 5, 5, 7, 6, 6, 7, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5,
       6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5,
       5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 7, 7, 6, 5, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 7, 5, 6, 5, 6,
       5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 5, 7, 5, 6, 6, 5,
       5, 5, 7, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 6,

In [29]:
accuracy_score(y_pred=previsoes_random_forest_wine, y_true=y_wine_teste)

0.721875

MODELO KNN

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
knn_wine = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn_wine.fit(X_wine_treinamento, y_wine_treinamento)

KNeighborsClassifier()

In [68]:
previsoes_knn = knn_wine.predict(X_wine_teste)
previsoes_knn 

array([5, 5, 7, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5,
       6, 6, 6, 5, 5, 7, 5, 6, 8, 6, 6, 5, 6, 6, 5, 5, 6, 7, 5, 7, 7, 5,
       6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 7, 6, 5, 5, 6, 6, 5, 6,
       5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 5, 7, 5, 6, 6, 6, 6, 5, 5, 5,
       6, 5, 5, 5, 6, 6, 7, 5, 6, 5, 5, 6, 7, 6, 5, 6, 5, 5, 5, 5, 6, 5,
       5, 5, 8, 5, 6, 6, 7, 7, 5, 6, 5, 5, 5, 5, 6, 7, 5, 5, 5, 7, 5, 5,
       6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 5, 6, 8, 6, 6, 5, 5, 5, 5, 6,
       5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 7, 6, 6,
       5, 7, 5, 5, 5, 7, 6, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 5, 5, 5, 5, 5,
       6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 6, 6, 5,
       5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 7, 6, 5, 7, 6, 6, 6, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6,
       5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 6, 6, 7, 6, 6, 5, 6, 6, 5,
       5, 5, 7, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6,

In [69]:
accuracy_score(y_pred=previsoes_knn, y_true=y_wine_teste)

0.60625

MODELO REGRESSÃO LOGÍSTICA

In [70]:
from sklearn.linear_model import LogisticRegression

In [71]:
logistic_wine = LogisticRegression(random_state=1)
logistic_wine.fit(X_wine_treinamento, y_wine_treinamento)

LogisticRegression(random_state=1)

In [74]:
previsoes_logistic = logistic_wine.predict(X=X_wine_teste)
previsoes_logistic

array([6, 5, 7, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 6, 7, 6, 6, 5, 6, 5,
       6, 7, 5, 5, 5, 6, 5, 7, 6, 6, 6, 5, 6, 6, 5, 6, 7, 6, 5, 6, 7, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 6, 5, 6,
       5, 6, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 7, 5,
       5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 6, 7, 5, 5,
       6, 6, 7, 5, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 6, 5, 6, 6, 5, 6,
       6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 7, 5, 6, 6, 5, 5, 7, 6, 6,
       6, 7, 6, 5, 5, 7, 5, 6, 7, 5, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 6, 5, 7, 5, 6, 6, 6, 6, 5,
       5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 7, 7, 6, 5, 5,
       5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6,
       5, 5, 5, 5, 6, 7, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 5, 7, 6, 6, 6, 5,
       5, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 5, 5, 6,

In [75]:
accuracy_score(y_pred=previsoes_logistic, y_true=y_wine_teste)

0.63125